import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const beausite = localFont({
	src: [
		{
			path: "./fonts/beausite-regular.ttf",
			weight: "400",
			style: "normal",
		},
		{
			path: "./fonts/beausite-bold.ttf",
			weight: "700",
			style: "normal",
		},
		{
			path: "./fonts/beausite-semibold.ttf",
			weight: "600",
			style: "normal",
		},
		{
			path: "./fonts/beausite-bolditalic.ttf",
			weight: "700",
			style: "italic",
		},
	],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${beausite.className} antialiased`}>{children}</body>
		</html>
	);
}
